In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = "/content/drive/MyDrive/merged.csv"
df = pd.read_csv(path)
df

       Geographic Area Name  Estimate!!Total:_race  ...  BROADBAND USAGE   ZCTA
0                     35004                  12045  ...            0.344  35004
1                     35005                   7344  ...            0.186  35005
2                     35006                   2883  ...            0.088  35006
3                     35007                  26332  ...            0.945  35007
4                     35010                  20613  ...            1.000  35010
...                     ...                    ...  ...              ...    ...
30466                 83124                    164  ...            0.253  83124
30467                 83126                    329  ...            0.000  83126
30468                 83127                   3597  ...            0.504  83127
30469                 83128                   1194  ...            1.000  83128
30470                 83414                    465  ...            0.085  83414

[30471 rows x 193 columns]

In [ ]:
cols = df.columns
cols

Index(['Geographic Area Name', 'Estimate!!Total:_race',
       'Estimate!!Total:!!White alone',
       'Estimate!!Total:!!Black or African American alone',
       'Estimate!!Total:!!American Indian and Alaska Native alone',
       'Estimate!!Total:!!Asian alone',
       'Estimate!!Total:!!Native Hawaiian and Other Pacific Islander alone',
       'Estimate!!Total:!!Some other race alone',
       'Estimate!!Total:!!Two or more races:',
       'Estimate!!Total:!!Two or more races:!!Two races including Some other race',
       ...
       'Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!Below poverty level',
       'Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!At or above the poverty level',
       'Estimate!!Unemployment rate!!Population 20 to 64 years!!DISABILITY STATUS!!With any disability',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher',
       'BROADBAND USAGE', 'ZCTA'],
      dtype='object', length=193)

In [ ]:
df2=df[cols].apply(pd.to_numeric, errors='coerce')
df2

       Geographic Area Name  Estimate!!Total:_race  ...  BROADBAND USAGE   ZCTA
0                     35004                  12045  ...            0.344  35004
1                     35005                   7344  ...            0.186  35005
2                     35006                   2883  ...            0.088  35006
3                     35007                  26332  ...            0.945  35007
4                     35010                  20613  ...            1.000  35010
...                     ...                    ...  ...              ...    ...
30466                 83124                    164  ...            0.253  83124
30467                 83126                    329  ...            0.000  83126
30468                 83127                   3597  ...            0.504  83127
30469                 83128                   1194  ...            1.000  83128
30470                 83414                    465  ...            0.085  83414

[30471 rows x 193 columns]

In [ ]:
df2["lessEDU_pct"]=df2['Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate']/df2['Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years']  
df2["hsEDU_pct"]=df2['Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)']/df2['Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years']  
df2

       Geographic Area Name  Estimate!!Total:_race  ...  lessEDU_pct  hsEDU_pct
0                     35004                  12045  ...     0.000000   1.409091
1                     35005                   7344  ...     6.727273   0.590909
2                     35006                   2883  ...     0.000000   1.454545
3                     35007                  26332  ...     1.568182   1.795455
4                     35010                  20613  ...     1.636364   1.045455
...                     ...                    ...  ...          ...        ...
30466                 83124                    164  ...     0.000000   0.000000
30467                 83126                    329  ...          NaN        NaN
30468                 83127                   3597  ...     0.000000   1.840909
30469                 83128                   1194  ...          NaN        NaN
30470                 83414                    465  ...          NaN        NaN

[30471 rows x 195 columns]

In [ ]:
df2 = pd.DataFrame(df2)
df2.to_excel('df2.xlsx', sheet_name = 'New_sheet')

NameError: ignored

# New Section

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive,force_remount=True')

ValueError: ignored

In [ ]:
path = "/content/drive/MyDrive/Merged_data_for_analysis_6.27.csv"
df = pd.read_csv(path)
df

OSError: ignored